sudo: false
language: cpp

install: 
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C ./
  - export PATH=$PATH:$PWD
  - echo $PATH
  - echo $HOME
env:
  - JOB=ONE
  - JOB=TWO
 
script:
  - testspace test.xml $TESTSPACE_TOKEN/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}#travis.Bld.${TRAVIS_BUILD_NUMBER}.Job.${TRAVIS_JOB_NUMBER}