sudo: false
language: cpp
install:
  - mkdir -p ~/.local/bin; curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C ~/.local/bin
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  
env:
  matrix:
  - JOB=ONE
  - JOB=TWO
  global:
    secure: V2oxDG75drbQe//SLSclfLg9HUQ8MLGISZL74sa1YwvA8RJMQpFGLhJ43lDsRWEsfBzbJ4JBAvIuvpCSnx/mZlNZJ+9m2gQREWizXR91474JfgFAMwuOYNSYkeoe51ToZSS5sh45awidIga4wenI3bH+OnC3A9p/BcGMhlJJmxTnxl0gu/VoQkkOPyqjTEjrtbKcEbkzQ6WucV+NjbfVyRshvp0tvItxvNgp6XvKeBxLu+Q1y80BSPZN7Qxk0BWjlAl7k1bdYwln67zTT8H/NakVm328sflcoXJhLtRixUhYON0JBrAFeDYY2hlP2WB8mqRU+dPZVWBhhk5UW2VIgYuK7C1GkOdOtYZDds/wkl5Jro4+I+Gnv4sh6cpT67QPr8hHmI1yOKLQJs2F670b8plzTRbCRJRgARahffJPNxx5cAY36PXS10LroICjRd1aT9pKo9D/AUGkRrTjjr0JZbhIMOiZ2hv8KZhKYSmAQD2MnldY0dPyuHGvli+wO6zBlCKWGXJ7pre2al+lgm8wUxUKSKQog7ItPSxI3pln+xagobm8XDlTSuIKU1t7QzMeRmKOdxL1Bdv2f4YzdmCQ5NT9wU2XXpRq+keH7G6dZ1+gj4vse9YQHdkrlJ5ygSV3ywn8WfDUKfgcz9UwZgHEp8p2mRGfU3YqsOq6ITBgjnM=
   

#script:
# - testspace test.xml $TESTSPACE_TOKEN/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}.Job.${TRAVIS_JOB_NUMBER}

before_script:
  - export TS_URL=$TESTSPACE_TOKEN/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}\#travis.Build.${TRAVIS_BUILD_NUMBER}
  - if [ "${TRAVIS_JOB_NUMBER#*.}" -eq "1" ] ; then testspace $TS_URL?start ; fi
  
#script:
 
after_script:
  - testspace test.xml $TS_URL?add
  - python travis_after_all.py https://api.travis-ci.org
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
          testspace $TS_URL?finish
      fi
