language: cpp

# Requires TESTSPACE_TOKEN environment variable.   
after_script:
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace test.xml http://sandio:$TESTSPACE_TOKEN@96ec4091.ngrok.io/${TRAVIS_REPO_SLUG/\//:}/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
